name: Dockerize FastAPI Application

on:
  push:
    branches:
      - master  # Adjust branch as needed
  pull_request:
    branches:
      - master  # Adjust branch as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub (optional, if you want to push the image)
      # You need to store your Docker Hub credentials in GitHub Secrets (DOCKER_USERNAME, DOCKER_PASSWORD)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image for FastAPI
      - name: Build Docker image
        run: |
          docker build -t todoapp-fastapi:latest .

      # Step 5: Push Docker image to Docker Hub (optional)
      - name: Push Docker image to Docker Hub
        run: |
          docker tag todoapp-fastapi:latest ${{ secrets.DOCKER_USERNAME }}/todoapp-fastapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/todoapp-fastapi:latest

  run-local:
    # Run only when pushing to a local branch (replace 'local' with your branch name)
    if: github.ref == 'refs/heads/local'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t todoapp-fastapi:latest .

      # Step 3: Run the container locally
      - name: Run FastAPI container locally
        run: docker run -d -p 8000:8000 --name fastapi-app todoapp-fastapi:latest
